- lib/client.js
This is a fix to this issue: https://github.com/parse-community/parse-server/issues/6057
The changes are collected from the PR to the original `node-apn` repository:
* https://github.com/node-apn/node-apn/pull/642
* https://github.com/node-apn/node-apn/pull/643
They are known to fix the issue according to this thread: https://github.com/node-apn/node-apn/issues/640
> Add support for handling http2 GOAWAY messages and set http2 ping interval

- lib/client.js
Use [`http2session.close([callback])`](https://nodejs.org/api/http2.html#http2_http2session_close_callback) instead.
```
(node:58669) UnhandledPromiseRejectionWarning: TypeError: this.session.shutdown is not a function
at Client.shutdown (/Code/pushy-api/node_modules/@parse/node-apn/lib/client.js:144:20)
at Provider.shutdown (/Code/pushy-api/node_modules/@parse/node-apn/lib/provider.js:46:17)
at exports.publish.apnsProvider.send.then (/Code/pushy-api/logic/push/platforms/ios.js:122:30)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
> Fix: http2session.shutdown() is not a function

- .travis.yml
Currently, `coveralls` is added as a normal dependency so all users are forced to install it too.
> Install coveralls as a dev dependency on publish

- index.d.ts
Added a specific type for Notification.pushType, rather than typing it as a generic `string`.
> Typed Notification.pushType

- README.md
I'm not sure which make sense to change here
and what the remaining equivalent are.
For example, it would make sense to properly indicate whether
@parse/node-apn has up to date dependencies.
https://nodei.co/ seems to have issues with `@a/b` package names and doesn't show download statistics.
> Update some of the urls in README for parse

- .travis.yml
Node 14 will become an LTS release in October.
> Also run tests in Node 12 and 14

- index.d.ts
In the original project, we left status as a string: https://github.com/node-apn/node-apn/blob/master/lib/client.js#L80
In this fork, with the new http2 code, it's a number: https://github.com/parse-community/node-apn/blob/master/lib/client.js#L124
> Change ResponseFailure.status typing to be number

- doc/provider.markdown
This used to be a string in the original project, [but now seems to be a number](https://github.com/parse-community/node-apn/pull/16).
> Fix status code type in code example

- .github/workflows/ci.yml
- README.md
- package-lock.json
- package.json
Migrating from coveralls to fix CI. This is consistent with the rest of the repositories.
> chore: Move coverage to codecov

- lib/notification/index.js
- test/notification/index.js
This was proposed by @n8ham, on node-apn/node-apn repository, the text
below was written by him.
The value of the `expiry` field is passed to the `apns-expiration`
header. This is Apple's documentation for that header:
> The date at which the notification is no longer valid. This value is a
> Unix epoch expressed in seconds (UTC). If the value is nonzero, APNs
> stores the notification and tries to deliver it at least once,
> repeating the attempt as needed until the specified date. If the value
> is 0, APNs attempts to deliver the notification only once and does not
> store the notification.
node-apn should therefore support `0` as a value for `expiry`, enabling
users to request notifications that are attemted only once. Instead of
`0` we can use `-1` as a flag for "unset", since …
> fix: add support to zero valued expiry

- lib/config.js
- test/config.js
This is the most recent Apple's documentation:
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
> Establish a Connection to APNs
> Use HTTP/2 and TLS 1.2 or later to establish a connection between your
> provider server and one of the following servers:
> - Development server: api.sandbox.push.apple.com:443
> - Production server: api.push.apple.com:443
To keep in sync with Apple's documentation, EndpointAddress.development
should be updated.
> Update endpoint address

- index.d.ts
- lib/client.js
- package-lock.json
- package.json
- test/client.js
For the sake of backwards compatibility, continue requiring DEBUG=apn to
log either of these.
For the sake of convenience, allow applications to manually override
these loggers on a per-Client instance basis.
A more fully-featured logger such as error/warn/info/debug might be
useful but overkill if the error conditions are rare in practice.
Related to https://github.com/parse-community/node-apn/issues/59
High volume uses of node-apn may benefit from logging errors but ignore
non-errors.
Related to https://github.com/parse-community/node-apn/issues/30
- setLogger can be used by applications to set their own prefix
> Proposal: Add a configurable info/error logger

- lib/client.js
(For frame errors not associated with a known request)
This is using the standard library's http2 library, so if there is a frame
error, something unexpectedly went wrong on this client or on the remote
server. This shouldn't happen in normal circumstances.
Try to disconnect and establish a new connection
Fixes https://github.com/parse-community/node-apn/issues/64
> Close client on unexpected frame error

- lib/client.js
- lib/util/proxy.js
- test/client.js
Hello!
This PR adds proxy support for native https2.
Proxy support [is already documented](https://github.com/parse-community/node-apn#connecting-through-an-http-proxy), but in fact it is only present in [the `node-apn/node-http2` based versions](https://github.com/node-apn/node-apn/blob/3.0.0/lib/protocol/endpoint.js#L84).
> Proxy support

- .github/workflows/ci.yml
- ChangeLog.md
- README.md
- index.d.ts
- index.js
- lib/client.js
- lib/multiclient.js
- mock/client.js
- mock/index.js
- package-lock.json
- package.json
- test/multiclient.js
- test/provider.js
It is possible for some use cases to run into limits on the number of
in-flight requests to APNs at a time, especially when sending out bursts
of push notifications.
It seems like this is only necessary when sending out over a hundred
pushes per second, though that may depend on the burstiness, cpu speed or
internet reliability.
And drop support for node < 12 - they have known crashes/bugs with http2 that I don't expect to get fixed (security fixes only).
Refactorings such as this PR may make those bugs more likely.
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns/ mentions the following
> Avoid push burst over selective connections. Diversifying push traffic over many connections distributes push …
> Proposal: Implement a round-robin MultiClient, drop support for node < 12

- doc/notification.markdown
- lib/notification/apsProperties.js
- lib/notification/index.js
- test/notification/apsProperties.js
A copy of the PR on https://github.com/Netatmo/node-apn/pull/6
See more [here](https://developer.apple.com/videos/play/wwdc2021/10091/), [here](https://developer.apple.com/documentation/usernotifications/unnotificationinterruptionlevel?changes=la) and [here](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification).
> Added support for iOS 15 property interruption-level

- doc/notification.markdown
- lib/notification/apsProperties.js
- lib/notification/index.js
- test/notification/apsProperties.js
See `target-content-id` [here](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2943361) and [here](https://developer.apple.com/documentation/usernotifications/unnotificationcontent/3235764-targetcontentidentifier).
> Add support for target-content-id notification property

- lib/notification/index.js
- package.json
- test/credentials/certificate/parse.js
- test/credentials/certificate/prepare.js
- test/notification/apsProperties.js
- test/notification/index.js
Summary of changes:
- updated the `test` and `coverage` scripts to run all test files in the test folder: `'test/**/*.js'`
- added missing setter method for `targetContentIdentifier` property
- updated multiple tests so that they are now passing (fresh clone of repo had 76 failing tests)
> Updated test scripts to run tests in sub folders and updated failing tests

- .github/workflows/ci.yml
- README.md
- doc/notification.markdown
- lib/notification/apsProperties.js
- lib/notification/index.js
- test/client.js
- test/notification/apsProperties.js
https://developer.apple.com/documentation/activitykit/updating-and-ending-your-live-activity-with-activitykit-push-notifications
This PR also fixes the broken tests.
> feat: Add support for Live Activity with ActivityKit push notifications

- lib/provider.js
- test/provider.js
Pass the optional shutdown callback from the Provider through to the Client.
fix #117
> fix: Shutdown callback is not passed from provider to client

- README.md
- doc/notification.markdown
- lib/notification/apsProperties.js
- lib/notification/index.js
- test/notification/apsProperties.js
Per the documentation https://developer.apple.com/documentation/activitykit/updating-and-ending-your-live-activity-with-activitykit-push-notifications
`event` should be `events`
> fix: Incorrect field name `event` instead of `events` in Live Activity push notification payload

- .github/workflows/ci.yml
- test/client.js
- test/multiclient.js
- test/notification/apsProperties.js
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#nodejs
There was a fix in the http2 module to correctly handle errors. Before we had to parse the error in the `end` event now its handled on `error` emitter on client requests.
Closes: #132
This PR is referencing #131, which has now been closed.
> feat: Add support for Node 18, 20 drop support for Node 12

- package.json
> fix: Minimum required Node version in `engines.node` has not been upgraded to Node 14

- README.md
- doc/notification.markdown
- lib/notification/apsProperties.js
- lib/notification/index.js
- test/notification/apsProperties.js
Closes: #133
Live Activity push notification payload #133
This reverts commit a25c835d220a6d37101eeaedaec78e1fb0028696.
Continuation of #136
> fix: Incorrect field name `events` instead of `event` in Live Activity push notification payload

- package-lock.json
- package.json
Supersedes https://github.com/parse-community/node-apn/pull/147.
Fixes a vulnerability and reduces the number of dependencies (`lodash`).
> fix: Security upgrade jsonwebtoken from 9.0.0 to 9.0.2

- .github/workflows/ci.yml
- README.md
Fix code coverage and update CI to latest versions.
> ci: Fix code coverage reporting

- README.md
- doc/provider.markdown
- index.d.ts
- lib/client.js
- lib/config.js
- lib/multiclient.js
- lib/notification/index.js
- lib/provider.js
- lib/util/proxy.js
- mock/client.js
- test/client.js
- test/config.js
- test/multiclient.js
- test/notification/index.js
- test/provider.js
- test/proxy.js
Continuation of #163 which allowed the additional properties needed for broadcast notifications, but doesn't modify the Client API to `GET`, `POST`, `DELETE` to the respective Apple paths.
Closes: #162
Closes: #146
Closes: #111
Closes: #116
Follow the documentation related to [channel management](https://developer.apple.com/documentation/usernotifications/sending-channel-management-requests-to-apns) and [broadcasting](https://developer.apple.com/documentation/usernotifications/sending-broadcast-push-notification-requests-to-apns). This enables the functionality described in Apple's WWDC 2024 videos: [Broadcast Updates to Your Live Activities](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://developer.apple.com/videos/play/wwdc2024/10069/&ved=2ahUKEwjT-9HqgNiKAxWyIk …
> feat: Add the ability to manage channels and send broadcasts

- .github/workflows/ci.yml
- lib/client.js
- test/client.js
- test/notification/index.js
PR #164 introduced the ability to `GET` and `DELETE` to add functionality for channel management. Previously, the API could only `POST`, which always required a `body` to be sent. In cases of `GET` and `DELETE`, a body shouldn't be sent. #164 attempts to only send a body when necessary but incorrectly assumes the body is an `Object` when it is always a JSON string.
This checks against an empty JSON string and adds a test to verify the body is a JSON string and not an `Object`.
Closes: #168
> fix: Incorrectly attempting to send body in `GET`, `DELETE` requests

- package-lock.json
- package.json
> refactor: Bump debug from 4.3.3 to 4.4.0

- lib/notification/index.js
- test/notification/index.js
Allows the priority of `10` to be sent to the APN server. Previously, the library didn't omit the value of `10` because the APN server uses this value as default. For broadcast messages, this may not be the case, so the change sends the value regardless.
The original default behavior from a developer using the library is still the same. Basically, if the dev doesn't specify a priority, the default is still `10`.
Closes: #172
> fix: Does not allow sending the priority of 10 for notifications

- index.d.ts
- lib/notification/apsProperties.js
- lib/notification/index.js
- test/notification/apsProperties.js
Closes: #176 
Add new fields for Live Activities in TS and JS:
Add missing properties and set methods for APS in JS:
> feat: Add `input-push-channel` and `input-push-token` to APS
